spring.application.name=api-gateway
server.port=8084

# ===== JWT =====
app.jwt.secret=${JWT_SECRET:super_long_random_secret_key_at_least_32_chars}

# ===== BASE URL ??? WEBCLIENT (RegistrationService ? ?.?.) =====
services.user.base-url=${USER_SERVICE_URL:http://localhost:8081}
services.auth.base-url=${AUTH_SERVICE_URL:http://localhost:8082}
# ???? ????? ???-?? ????? ?????
services.order.base-url=${ORDER_SERVICE_URL:http://localhost:8083}

# ===== ROUTES =====

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/register,/auth/login,/auth/validate,/auth/refresh

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=${USER_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**,/api/cards/**

spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=${ORDER_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**
