spring.application.name=api-gateway
server.port=8084

services.auth-url=${AUTH_URL:http://auth-service:8082}
services.user-url=${USER_URL:http://user-service:8080}
services.order-url=${ORDER_URL:http://order-service:8083}

spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=${services.auth-url}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/users/**

spring.cloud.gateway.routes[1].id=user
spring.cloud.gateway.routes[1].uri=${services.user-url}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**,/api/cards/**

spring.cloud.gateway.routes[2].id=order
spring.cloud.gateway.routes[2].uri=${services.order-url}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**
